# Generated by Django 5.2.3 on 2025-07-26 14:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_name', models.CharField(choices=[('EN', 'English'), ('FC', 'French'), ('GR', 'Germany'), ('IT', 'Italian'), ('SP', 'Spain'), ('AR', 'Arabic')], default='EN', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('BC', 'Basic'), ('IN', 'Intermediate'), ('AV', 'Advance')], default='BC', max_length=2)),
                ('sessions', models.IntegerField()),
                ('status', models.CharField(choices=[('RG', 'Registering'), ('ST', 'Started'), ('CN', 'Canceled')], default='RG', max_length=2)),
                ('start', models.DateField(default=django.utils.timezone.now)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class.language')),
            ],
            options={
                'ordering': ['-level', '-start'],
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('stu_serial', models.CharField(max_length=14)),
                ('level', models.CharField(choices=[('BC', 'Basic'), ('IN', 'Intermediate'), ('AV', 'Advance')], default='BC', max_length=2)),
                ('number', models.CharField(max_length=12)),
                ('age', models.CharField(max_length=12)),
                ('class_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class.classes')),
                ('lang_choices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class.language')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('year_of_teach', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=12)),
                ('lang_spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class.language')),
            ],
        ),
        migrations.AddField(
            model_name='classes',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class.teacher'),
        ),
    ]
