# Generated by Django 5.2.3 on 2025-08-11 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='class_choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='class.classes'),
        ),
        migrations.AlterField(
            model_name='students',
            name='lang_choices',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='class.language'),
        ),
    ]
